# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  primary:
    database: agtech_development
    adapter: postgis
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    encoding: unicode
    host: 127.0.0.1
    postgis_extension: postgis # default is postgis
    postgis_schema: public # default is public
    schema_search_path: public,postgis
    username: ekylibre # the username your app will use to connect
    password: ekylibre # the user's password
    su_username: ekylibre # a superuser for the database
    su_password: ekylibre # the superuser's password
  lexicon:
    database: eky_development
    database_tasks: false
    adapter: postgis
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    encoding: unicode
    host: 127.0.0.1
    postgis_extension: postgis # default is postgis
    postgis_schema: public # default is public
    username: ekylibre # the username your app will use to connect
    password: ekylibre # the user's password
    su_username: ekylibre # a superuser for the database
    su_password: ekylibre # the superuser's password
    schema_search_path: lexicon,postgis,public
